# Generated by Django 6.0.3 on 2026-04-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_client_user_id_appointment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('is_open', models.BooleanField(default=True)),
                ('work_start', models.TimeField(default='08:00')),
                ('work_end', models.TimeField(default='18:00')),
                ('lunch_start', models.TimeField(default='12:00')),
                ('lunch_end', models.TimeField(default='13:00')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='booking.professionalprofile')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('professional', 'day_of_week')},
            },
        ),
    ]
