# Generated by Django 6.0.3 on 2026-04-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_openinghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data Bloqueada')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Fim')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='booking.professionalprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
