# Generated by Django 6.0.3 on 2026-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_add_portfolio_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_url',
            field=models.URLField(max_length=2000, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL da Foto'),
        ),
    ]
