# Generated by Django 6.0.3 on 2026-04-16 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_portfolioitem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.professionalprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='professional',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.professionalprofile'),
            preserve_default=False,
        ),
    ]
