# Generated by Django 6.0.3 on 2026-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_professionalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
