# Generated by Django 6.0.3 on 2026-03-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_professionalprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
