# Generated by Django 6.0.3 on 2026-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Usuário (Clerk)')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Profissional')),
                ('description', models.TextField(blank=True, verbose_name='Bio/Descrição')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL da Foto')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('is_setup_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
